language: java
jdk:
- openjdk8
install:
- mvn -N io.takari:maven:wrapper
- "./mvnw install -DskipTests=true -Dmaven.javadoc.skip=true -B -V"
deploy:
  skip_cleanup: true
  provider: heroku
  api_key: $HEROKU_TOKEN