language: java
jdk:
- openjdk8
install:
- mvn -N io.takari:maven:wrapper
- "./mvnw install -DskipTests=true -Dmaven.javadoc.skip=true -B -V"
deploy:
  skip_cleanup: true
  provider: heroku
  api_key:
    secure: ggspvFrj2HzTbFtBavMV8qF2bppvjZe3I3isFZ8+LWo7fW6ll0kqyy9sPS67nQMVvdJvGtiG9E4IHQwcjhOpHK0EmBbFEzpvjNOWfe4hNjx2pS5N3PLOBVLOU8LSEOP+6vOBTn0ejn9vmbFeuK8KPV9TuC6+AtHJpwwk7uJJWkwFV1iskFBQjNz5DgvFFBQt4RBnVDYsnf0W0og1c+fWXiAW5QpUPvVoitVBXCe4a59iXmFP2lbh0gnC+WwaHfg/MgNPnP/hBXbPf9x4i+mrVJUzv661tnSrD9b0Vs1ucdCeah/oxTe/tAYZQwcS422gNXvIPIqV9EiqCiKBvCLeI5M2u2VYBVUOFAmXHSs4qJiQQdu4i3omlyPFbKb8nzQ+ADFFmC1pNgc7qLY/XOQxhzqZCIlzmuN3n4G2+/PyRrHuvFOexM/usi8uevu1CK2BWS58dmM/4s3awNCHO8cD+qy7DkzGy5oK+PNT0hNkh1u66PLIIQYD96C8n0ccBjWUJQhWgFGJ0hDNHNZ/yGzCp5GdWG42bSfrwqikxKQuu+j2A0SvkuAF6CUlTLUw88eMq/z247PwUSYgJ8Ehk0n5epYOUVNhWDZeFIXaHXD6e5NZ/a4ONtgaatm2WIyERz7NNjCWeLtkq6a4k2jgsDljV6PIx9JmptSaYrZL3VKnvQI=
